# This configuration only includes the cops that differ from the Rubocop
# defaults, which can be found here:
# https://github.com/bbatsov/rubocop/blob/master/config/default.yml
# https://github.com/bbatsov/rubocop/blob/master/config/enabled.yml
# https://github.com/bbatsov/rubocop/blob/master/config/disabled.yml

AllCops:
  Include:
    - '**/Gemfile'
    - '**/Rakefile'
    - 'lib/**/*'
    - 'spec/**/*'
  Exclude:
    - 'bin/**/*'
  TargetRubyVersion: 3.3

Metrics/BlockLength:
  CountComments: false  # count full line comments?
  Enabled: true
  Max: 25
  Exclude:
    - 'spec/**/*.rb'

Metrics/LineLength:
  Description: Limit lines to 100 characters.
  StyleGuide: https://github.com/bbatsov/ruby-style-guide#80-character-limits
  Enabled: true
  Max: 100
  AllowURI: true
  URISchemes:
  - http
  - https
  Exclude:
    - 'config/routes.rb'

Style/DoubleNegation:
  Enabled: false
